# ---------------------------------------------
# Archon Plugin Configuration
# ---------------------------------------------
# Plugin Name: Archon
# Plugin Version: 1.0
# Made by: Asfaltios Advanced
# Discord: https://discord.gg/ESZtT2aDS3
# ---------------------------------------------
# Description:
# Archon is an advanced Minecraft admin tool plugin designed
# to simplify server management and offer powerful in-game
# features for server admins.
#
# Configuration settings for Archon plugin.
# This will be expanded in the future.
# ---------------------------------------------

