name: Archon
main: com.asfaltios.archon.Archon
version: 1.1
api-version: 1.21
author: Asfaltios Advanced
description: A comprehensive admin plugin with advanced GUI.

commands:
  admin:
    description: Opens the Archon Admin GUI.
    usage: /admin [reload]
    permission: archon.admin
    aliases: [archon]

permissions:
  archon.admin:
    description: Allows access to the main admin command.
    default: op
    children:
      archon.admin.playermanagement: true
      archon.admin.servermanagement: true
      archon.admin.personaltools: true
      archon.admin.reload: true

  archon.admin.reload:
    description: Allows reloading the plugin.
    default: op

  archon.admin.playermanagement:
    description: Allows access to player management features.
    default: op
    children:
      archon.admin.playermanagement.kick: true
      archon.admin.playermanagement.ban: true
      archon.admin.playermanagement.mute: true
      archon.admin.playermanagement.freeze: true
      archon.admin.playermanagement.teleportto: true
      archon.admin.playermanagement.bring: true
      archon.admin.playermanagement.inspect: true
      archon.admin.playermanagement.permission: true
      archon.admin.playermanagement.message: true
      archon.admin.playermanagement.heal: true
      archon.admin.playermanagement.feed: true
      archon.admin.playermanagement.sethealth: true

  archon.admin.playermanagement.kick:
    description: Allows kicking players.
    default: op

  archon.admin.playermanagement.ban:
    description: Allows banning players.
    default: op

  archon.admin.playermanagement.mute:
    description: Allows muting players.
    default: op

  archon.admin.playermanagement.freeze:
    description: Allows freezing players.
    default: op

  archon.admin.playermanagement.teleportto:
    description: Allows teleporting to players.
    default: op

  archon.admin.playermanagement.bring:
    description: Allows bringing players to you.
    default: op

  archon.admin.playermanagement.inspect:
    description: Allows inspecting players' inventories.
    default: op

  archon.admin.playermanagement.permission:
    description: Allows modifying player permissions.
    default: op

  archon.admin.playermanagement.message:
    description: Allows sending private messages to players.
    default: op

  archon.admin.playermanagement.heal:
    description: Allows healing players.
    default: op

  archon.admin.playermanagement.feed:
    description: Allows feeding players.
    default: op

  archon.admin.playermanagement.sethealth:
    description: Allows setting players' health.
    default: op

  archon.admin.servermanagement:
    description: Allows access to server management features.
    default: op
    children:
      archon.admin.servermanagement.changetime: true
      archon.admin.servermanagement.changeweather: true
      archon.admin.servermanagement.manageworlds: true
      archon.admin.servermanagement.serverstats: true
      archon.admin.servermanagement.executecommand: true
      archon.admin.servermanagement.manageplugins: true
      archon.admin.servermanagement.whitelist: true
      archon.admin.servermanagement.viewlogs: true

  archon.admin.servermanagement.changetime:
    description: Allows changing the time.
    default: op

  archon.admin.servermanagement.changeweather:
    description: Allows changing the weather.
    default: op

  archon.admin.servermanagement.manageworlds:
    description: Allows managing worlds.
    default: op

  archon.admin.servermanagement.serverstats:
    description: Allows viewing server statistics.
    default: op

  archon.admin.servermanagement.executecommand:
    description: Allows executing server commands.
    default: op

  archon.admin.servermanagement.manageplugins:
    description: Allows managing plugins.
    default: op

  archon.admin.servermanagement.whitelist:
    description: Allows managing the server whitelist.
    default: op

  archon.admin.servermanagement.viewlogs:
    description: Allows viewing server logs.
    default: op

  archon.admin.personaltools:
    description: Allows access to personal admin tools.
    default: op
    children:
      archon.admin.personaltools.togglefly: true
      archon.admin.personaltools.godmode: true
      archon.admin.personaltools.heal: true
      archon.admin.personaltools.giveitem: true
      archon.admin.personaltools.enderchest: true
      archon.admin.personaltools.togglegamemode: true
      archon.admin.personaltools.vanish: true
      archon.admin.personaltools.speed: true

  archon.admin.personaltools.togglefly:
    description: Allows toggling fly mode.
    default: op

  archon.admin.personaltools.godmode:
    description: Allows toggling god mode.
    default: op

  archon.admin.personaltools.heal:
    description: Allows healing yourself.
    default: op

  archon.admin.personaltools.giveitem:
    description: Allows giving yourself items.
    default: op

  archon.admin.personaltools.enderchest:
    description: Allows opening your ender chest.
    default: op

  archon.admin.personaltools.togglegamemode:
    description: Allows toggling your game mode.
    default: op

  archon.admin.personaltools.vanish:
    description: Allows toggling vanish mode.
    default: op

  archon.admin.personaltools.speed:
    description: Allows setting your movement speed.
    default: op
